# Generated by Django 4.0.3 on 2022-04-28 17:49

import cloudinary.models
import cook_book.cook_book_profiles.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cook_book_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookBookUserProfile',
            fields=[
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('first_name', models.CharField(blank=True, error_messages={'min_length': 'Името трябва да съдържа поне две букви!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(2), cook_book.cook_book_profiles.validators.only_letters_validator])),
                ('last_name', models.CharField(blank=True, error_messages={'min_length': 'Името трябва да съдържа поне две букви!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(2), cook_book.cook_book_profiles.validators.only_letters_validator])),
                ('joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
