# Generated by Django 4.0.3 on 2022-04-10 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookuserprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
