# Generated by Django 4.0.3 on 2022-04-14 19:53

import cook_book.cook_book_profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_profiles', '0002_alter_cookbookuserprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookuserprofile',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'min_length': 'Името трябва да съдържа поне две букви!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(2), cook_book.cook_book_profiles.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='cookbookuserprofile',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'min_length': 'Името трябва да съдържа поне две букви!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(2), cook_book.cook_book_profiles.validators.only_letters_validator]),
        ),
    ]
