# Generated by Django 4.0.3 on 2022-04-14 20:02

import cloudinary.models
import cook_book.cook_book_profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_profiles', '0004_alter_cookbookuserprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookuserprofile',
            name='first_name',
            field=models.CharField(blank=True, default=1, error_messages={'min_length': 'Името трябва да съдържа поне две букви!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(2), cook_book.cook_book_profiles.validators.only_letters_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookbookuserprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
