# Generated by Django 4.0.3 on 2022-04-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookcustomuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Този e-mail е вече регистриран.'}, max_length=254, unique=True),
        ),
    ]
