# Generated by Django 4.0.3 on 2022-04-14 18:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_auth', '0003_cookbookcustomuser_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cookbookcustomuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
