# Generated by Django 4.0.3 on 2022-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_auth', '0004_alter_cookbookcustomuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbookcustomuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
