# Generated by Django 4.0.3 on 2022-04-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_auth', '0005_cookbookcustomuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cookbookcustomuser',
            managers=[
            ],
        ),
    ]
