# Generated by Django 4.0.3 on 2022-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book_main_app', '0004_alter_cookedmeal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedmeal',
            name='type',
            field=models.CharField(choices=[('Предястия', 'Предястия'), ('Тестени изделия', 'Тестени изделия'), ('Торти', 'Торти'), ('Сладкиши', 'Сладкиши'), ('Основни ястия', 'Основни ястия'), ('Здравословни', 'Здравословни')], max_length=15),
        ),
    ]
